name: Verify Build

on:
  push:
    branches:
      - '*'
    paths:
      - 'xplib/**'
      - 'scripts/**'
      - 'CMakeLists.txt'
      - 'tests/**'
      - 'cmake/**'
      - '.github/workflows/build.yml'

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
